from rhyme_rus.utils.word import Word
from rhyme_rus.utils.procedure import Procedure

word = Word("сорт")
word = Procedure(word).build()

print("unstressed_word", word.unstressed_word)
print("stressed_vowel", word.stressed_vowel)
print("all_stressed", word.all_stresses)
print("stressed_word", word.stressed_word)
print("intipa", word.intipa)
print("all_scope_rhymes_dict", len(word.all_scope_rhymes_dict))
print("all_scope_rhymes_dict", list(word.all_scope_rhymes_dict.items())[:3])
print("_______________")
# print("all_scope_rhymes_intipa", len(word.all_scope_rhymes_intipa))
# print("all_scope_rhymes_intipa", word.all_scope_rhymes_intipa[:3])
# print("_______________")
print("all_scope_pads_dict", len(word.all_scope_pads_dict))
print("all_scope_pads_dict", list(word.all_scope_pads_dict.items())[8000:8003])
print("len of unique values all_scope_pads_dict", len(set(word.all_scope_pads_dict.values())))
print("_______________")
# print("all_scope_pads_list", len(word.all_scope_pads_list))
# print("all_scope_pads_list", word.all_scope_pads_list[:3])
# print("_______________")
print("all_rhymes_patterns_dict", len(word.all_rhymes_patterns_dict))
print("all_rhymes_patterns_dict", list(word.all_rhymes_patterns_dict.items())[:3])
print("_______________")
# print("all_rhymes_patterns_list", len(word.all_rhymes_patterns_list))
# print("all_rhymes_patterns_list", word.all_rhymes_patterns_list[:3])
# print("_______________")
# print("all_rhymes_scores_dict", len(word.all_rhymes_scores_dict))
# print("all_rhymes_scores_dict", list(word.all_rhymes_scores_dict.items())[:3])
print("_______________")
print("sum_scores")
for item in word.sum_scores.items(): print(item)

print("_______________")
print(word.score_rhymes)
print(word.score_rhymes.values())
total_rhymes = set()
for item in word.score_rhymes.values():
    total_rhymes.update(item)
print(len(total_rhymes))
