version: '3.4'
services:
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sql_1980
      MYSQL_USER: eugene
      MYSQL_PASSWORD: sql_1980
      MYSQL_DATABASE: rhymes
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports: 
      - 3307:3306 
  python:
    build:
      context: ./docker/python
    volumes:
      - .:/home/eugene